export const NEWS_CATEGORIES = [
  {
    id: "technology",
    name: "Technology",
    icon: "microchip",
    color: "text-primary",
    bgColor: "bg-blue-100",
    textColor: "text-blue-800",
    description: "Latest tech news, gadgets, and digital innovations",
  },
  {
    id: "business",
    name: "Business",
    icon: "chart-line",
    color: "text-emerald-500",
    bgColor: "bg-green-100",
    textColor: "text-green-800",
    description: "Market trends, companies, and economic updates",
  },
  {
    id: "science",
    name: "Science",
    icon: "flask",
    color: "text-violet-500",
    bgColor: "bg-purple-100",
    textColor: "text-purple-800",
    description: "Scientific discoveries, research, and breakthroughs",
  },
  {
    id: "health",
    name: "Health",
    icon: "heartbeat",
    color: "text-red-500",
    bgColor: "bg-red-100",
    textColor: "text-red-800",
    description: "Medical advances, wellness, and healthcare policy",
  },
  {
    id: "entertainment",
    name: "Entertainment",
    icon: "film",
    color: "text-amber-500",
    bgColor: "bg-amber-100",
    textColor: "text-amber-800",
    description: "Movies, music, celebrities, and pop culture",
  },
  {
    id: "sports",
    name: "Sports",
    icon: "futbol",
    color: "text-green-500",
    bgColor: "bg-green-100",
    textColor: "text-green-800",
    description: "Games, athletes, leagues, and sporting events",
  },
  {
    id: "politics",
    name: "Politics",
    icon: "landmark",
    color: "text-blue-700",
    bgColor: "bg-blue-100",
    textColor: "text-blue-800",
    description: "Elections, policies, government, and international relations",
  },
  {
    id: "environment",
    name: "Environment",
    icon: "leaf",
    color: "text-green-600",
    bgColor: "bg-green-100",
    textColor: "text-green-800",
    description: "Climate change, conservation, and sustainability",
  },
  {
    id: "finance",
    name: "Finance",
    icon: "money-bill-wave",
    color: "text-emerald-600",
    bgColor: "bg-emerald-100",
    textColor: "text-emerald-800",
    description: "Personal finance, investing, and economic policy",
  },
  {
    id: "general",
    name: "General",
    icon: "globe",
    color: "text-gray-600",
    bgColor: "bg-gray-100",
    textColor: "text-gray-800",
    description: "Top headlines and breaking news",
  },
];

export const DEFAULT_NEWS_IMAGE = 
  "https://images.unsplash.com/photo-1504711434969-e33886168f5c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80";

export const APP_NAME = "NewsFlow";
